import Head from 'next/head';
import WrongWayRacer from '@/components/games/WrongWayRacer';
import { WrongWayRacerStoreProvider } from '@/context/WrongWayRacer';
import PixiStageAutoresizeWrapper from '@/components/games/PixiStageAutoresizeWrapper';
import { LobbyStoreProvider } from '@/context';
import Lobby from '@/components/Lobby';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={
          'bg-wrong-way-racer-blue flex flex-col py-6 space-y-0 items-center px-6 md:px-0 font-saira'
        }
      >
        <LobbyStoreProvider>
          <WrongWayRacerStoreProvider>
            <PixiStageAutoresizeWrapper className="h-70v w-full max-w-5xl relative">
              {({ width, height }) => {
                return <WrongWayRacer width={width} height={height} className={'rounded-xl shadow-glow'} />;
              }}
            </PixiStageAutoresizeWrapper>
          </WrongWayRacerStoreProvider>

          <Lobby className="max-w-5xl h-30v" />
        </LobbyStoreProvider>
      </main>
    </>
  );
}
